require:
  - rubocop-rspec


Style/Encoding:
  Enabled: false
Style/LambdaCall:
  Enabled: false
Style/Documentation:
  Description: Document classes and non-namespace modules.
  Enabled: false
Style/KeywordParametersOrder:
  Enabled: false
Style/MissingRespondToMissing:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'HW04/*/spec/*'
    - 'HW03/*/spec/*'

NestedGroups:
  Exclude:
    - 'spec/**/*'
    - 'HW04/*/spec/*'
    - 'HW03/*/spec/*'

Style/For:
  Exclude:
    - 'HW02/**/*'

RSpec/NamedSubject:
  Exclude:
    - 'spec/**/*'
    - 'HW04/*/spec/*'
    - 'HW03/*/spec/*'

RSpec/DescribeClass:
  Exclude:
    - 'spec/**/*'
    - 'HW04/*/spec/*'
    - 'HW03/*/spec/*'

RSpec/ExpectActual:
  Exclude:
    - 'spec/**/*'
    - 'HW04/*/spec/*'
    - 'HW03/*/spec/*'

Layout/LineLength:
  Exclude:
    - 'spec/**/*'
    - 'HW04/*/spec/*'
    - 'HW03/*/spec/*'

RSpec/FilePath:
  Exclude:
    - 'spec/**/*'
    - 'HW03/*/spec/*'

Metrics/MethodLength:
  Exclude:
    - 'HW03/NameSurname/lizaveta_muromskaya_hw_03_t_03.rb'